### ISSUE TITLE
Save and Load from Disk

### ISSUE THREAD

**Issue by taylorgoolsby** [themaximal1st/vectordb.js#2]
I'm very excited to use this in my project, but I have one question.

I am trying to implement long term memory in an AI chatbot, so I need the ability to save the embeddings to disk and then load them back later.

Is there a way I can do this right now without any code changes, or make with some light monkey patching?

**Comment by taylorgoolsby** [comment]
I just looked through the docs for embeddings.js and I see the section on caching and `.embeddings.cache.json`. This looks like what I was looking for. Sorry to bother!

**Comment by themaximalist** [comment]
Great @taylorgoolsby — let me know if anything is needed around caching—there are probably some improvements that could be made.

**Comment by taylorgoolsby** [comment]
Hey @themaximal1st ! I tried it out, and loved the ease of setup and use, but I found that the custom object wasn't included in cache. Seems to only be in-memory only.

**Comment by themaximalist** [comment]
Thanks for the feedback @taylorgoolsby — I'll look into getting this added!
